package synapse.rest.dtos;

/**
 * Suggestions generated by the "brain" (AI/rules) from an inbox entry.
 */
public class BrainSuggestionDto {

    private String type;            // link, note, task, code, video...
    private String title;           // suggested title
    private String summary;         // distilled summary
    private String detailedContent; // detailed content in Markdown
    private String destination;     // note, idea, resource, task...
    private String[] tags;          // suggested tags

    // Optional: URL to the associated media resource (audio/video) and its MIME type
    private String mediaUrl;
    private String mediaContentType;

    public BrainSuggestionDto() {
    }

    public BrainSuggestionDto(String type, String title, String summary, String detailedContent,
            String destination, String[] tags, String mediaUrl, String mediaContentType) {
        this.type = type;
        this.title = title;
        this.summary = summary;
        this.detailedContent = detailedContent;
        this.destination = destination;
        this.tags = tags;
        this.mediaUrl = mediaUrl;
        this.mediaContentType = mediaContentType;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getDestination() {
        return destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    public String[] getTags() {
        return tags;
    }

    public void setTags(String[] tags) {
        this.tags = tags;
    }

    public String getDetailedContent() {
        return detailedContent;
    }

    public void setDetailedContent(String detailedContent) {
        this.detailedContent = detailedContent;
    }

    public String getMediaUrl() {
        return mediaUrl;
    }

    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }

    public String getMediaContentType() {
        return mediaContentType;
    }

    public void setMediaContentType(String mediaContentType) {
        this.mediaContentType = mediaContentType;
    }
}
